/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JCheckBox;
import javax.swing.JScrollPane;

/**
 *
 * @author Sairam
 */
public class home extends javax.swing.JPanel {

    public gVar g;

    /**
     * Creates new form home
     * @throws java.sql.SQLException
     */
    public home(gVar g) throws SQLException {
        this.g = g;
        initComponents();
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BookT = new javax.swing.JTable();

        setBackground(new java.awt.Color(1, 27, 29));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        BookT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BookT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B_Id", "B_Name", "Author", "No.", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BookT.setRowHeight(35);
        jScrollPane1.setViewportView(BookT);
        if (BookT.getColumnModel().getColumnCount() > 0) {
            BookT.getColumnModel().getColumn(0).setMinWidth(40);
            BookT.getColumnModel().getColumn(0).setPreferredWidth(40);
            BookT.getColumnModel().getColumn(0).setMaxWidth(40);
            BookT.getColumnModel().getColumn(1).setMinWidth(140);
            BookT.getColumnModel().getColumn(2).setMinWidth(100);
            BookT.getColumnModel().getColumn(3).setMinWidth(40);
            BookT.getColumnModel().getColumn(3).setPreferredWidth(40);
            BookT.getColumnModel().getColumn(3).setMaxWidth(40);
            BookT.getColumnModel().getColumn(4).setMinWidth(120);
            BookT.getColumnModel().getColumn(4).setPreferredWidth(120);
            BookT.getColumnModel().getColumn(4).setMaxWidth(200);
        }
        BookT.getColumn("Action").setCellRenderer(new ButtonRenderer("book",g));
        BookT.getColumn("Action").setCellEditor(new ButtonEditor(g,new JCheckBox(),"book",this,null));
        setSize( 400, 100 );
        setVisible(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BookT;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void updateTable() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) BookT.getModel();
        model.setRowCount(0);
        dbConn db = new dbConn();
        Statement stmt = db.conn.createStatement();
        ResultSet rs=stmt.executeQuery("select * from books");
        int columns = rs.getMetaData().getColumnCount();
        while(rs.next())
        {  
            Object[] row = new Object[columns];
            for (int i = 1; i <= columns; i++)
            {  
                row[i - 1] = rs.getObject(i);
            }
            ((DefaultTableModel)BookT.getModel()).insertRow(rs.getRow()-1,row);
        }
        return;
    }

  




}
