
import panels.login;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import javax.swing.JPanel;
import panels.home;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import panels.gVar;
import panels.Admin;
import panels.profile;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sairam
 */
public class LibManage extends javax.swing.JFrame implements ComponentListener {

    /**
     * Creates new form LibManage
     */
    GridBagLayout layout = new GridBagLayout();
    login signin;
    home home;
    profile profile;
    JPanel curr;
    gVar g = new gVar();
    Admin admin;
    public LibManage() throws ClassNotFoundException, SQLException {
        initComponents();
        Class.forName("com.mysql.jdbc.Driver");
        getContentPane().addComponentListener(this);
        profile = new profile(g);
        admin = new Admin();
        home = new home(g);
        signin = new login(SignUpB,SignIn,Profile,SignOutB,g,Admin,home,curr);
        this.curr = home;
        div.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        div.add(signin,c);
        div.add(home,c);
        div.add(profile,c);
        div.add(admin,c);
        signin.setVisible(false);
        HomeB.doClick();
        home.setVisible(true);
        profile.setVisible(false);
        admin.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        Menu = new javax.swing.JPanel();
        SignIn = new javax.swing.JButton();
        Profile = new javax.swing.JButton();
        SignUpB = new javax.swing.JButton();
        SignOutB = new javax.swing.JButton();
        Admin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        HomeB = new javax.swing.JButton();
        div = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management");
        setBounds(new java.awt.Rectangle(450, 150, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        Menu.setBackground(new java.awt.Color(1, 73, 80));

        SignIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panels/images/login.png"))); // NOI18N
        SignIn.setText("Sign In");
        SignIn.setBorder(null);
        SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInActionPerformed(evt);
            }
        });

        Profile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panels/images/profile2.png"))); // NOI18N
        Profile.setText("Profile");
        Profile.setBorder(null);
        Profile.setVisible(false);
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });

        SignUpB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SignUpB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panels/images/signup.png"))); // NOI18N
        SignUpB.setText("Sign Up");
        SignUpB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBActionPerformed(evt);
            }
        });

        SignOutB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SignOutB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panels/images/logout.png"))); // NOI18N
        SignOutB.setText("Sign Out");
        SignOutB.setBorder(null);
        SignOutB.setVisible(false);
        SignOutB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutBActionPerformed(evt);
            }
        });

        Admin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panels/images/admin.png"))); // NOI18N
        Admin.setText("Admin");
        Admin.setVisible(false);
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panels/images/menu.png"))); // NOI18N
        jLabel1.setText("Library Management");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        HomeB.setBackground(new java.awt.Color(255, 255, 255));
        HomeB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HomeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panels/images/home.png"))); // NOI18N
        HomeB.setText("Home");
        HomeB.setAlignmentY(0.0F);
        HomeB.setBorder(null);
        HomeB.setBorderPainted(false);
        HomeB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HomeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
            .addComponent(SignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SignOutB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SignUpB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HomeB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(HomeB, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(SignOutB, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(SignUpB, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(65, 66, 67));

        div.setBackground(new java.awt.Color(1, 27, 29));

        javax.swing.GroupLayout divLayout = new javax.swing.GroupLayout(div);
        div.setLayout(divLayout);
        divLayout.setHorizontalGroup(
            divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        divLayout.setVerticalGroup(
            divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(Menu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(div, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        getContentPane().add(jDesktopPane1);

        getAccessibleContext().setAccessibleName("Library Management");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInActionPerformed
        // TODO add your handling code here:
        curr.setVisible(false);
        curr = signin;
        curr.setPreferredSize(new Dimension(div.getSize()));
        curr.setVisible(true);
    }//GEN-LAST:event_SignInActionPerformed

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
        // TODO add your handling code here:
        curr.setVisible(false);
        curr = profile;
        curr.setPreferredSize(new Dimension(div.getSize()));
        curr.setVisible(true);
        try {
            profile.updateTable();
        } catch (SQLException ex) {
            Logger.getLogger(LibManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ProfileActionPerformed

    private void HomeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBActionPerformed
        // TODO add your handling code here:
        curr.setVisible(false);
        curr = home;
        curr.setPreferredSize(new Dimension(div.getSize()));
        curr.setVisible(true);
        try {
            home.updateTable();
        } catch (SQLException ex) {
            Logger.getLogger(LibManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_HomeBActionPerformed

    private void SignOutBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutBActionPerformed
        // TODO add your handling code here:
        g.user_id = -1;
        SignUpB.setVisible(true);
        SignIn.setVisible(true); 
        Profile.setVisible(false);
        SignOutB.setVisible(false);
        signin.setVisible(true);
        Admin.setVisible(false);
    }//GEN-LAST:event_SignOutBActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        // TODO add your handling code here:
        curr.setVisible(false);
        curr = admin;
        curr.setPreferredSize(new Dimension(div.getSize()));
        curr.setVisible(true);
    }//GEN-LAST:event_AdminActionPerformed

    private void SignUpBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBActionPerformed
        // TODO add your handling code here:
        curr.setVisible(false);
        curr = signin;
        curr.setPreferredSize(new Dimension(div.getSize()));
        curr.setVisible(true);
    }//GEN-LAST:event_SignUpBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new LibManage().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(LibManage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    private javax.swing.JButton HomeB;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton Profile;
    private javax.swing.JButton SignIn;
    private javax.swing.JButton SignOutB;
    private javax.swing.JButton SignUpB;
    private javax.swing.JPanel div;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentResized(ComponentEvent ce) {
         curr.setPreferredSize(new Dimension(div.getSize()));
        //System.out.println(div.getSize());
        
    }

    @Override
    public void componentMoved(ComponentEvent ce) {
         curr.setPreferredSize(new Dimension(div.getSize()));
    }

    @Override
    public void componentShown(ComponentEvent ce) {
    }

    @Override
    public void componentHidden(ComponentEvent ce) {
    }
}
